version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb_webapp-mongo-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase

  web:
    build:
      context: .
    container_name: mongodb_webapp-web-1
    ports:
      - "6543:6543"
    depends_on:
      - mongo
